config:
  hexapath-infra:projectName: hexapath
  hexapath-infra:customDomain:
    secure: AAABAHfaskoWFrKu3uHH2sh3zLYvJ1XRKdtqVUdtkFISkfmtvhLu60l4UHYgngGv9d3J
  hexapath-infra:accountId:
    secure: AAABAMx37jGJs443J4YOJFK/o4V8gmYb2m6p1sBZUc48SL7pxpSU7ny4pulgJKd9Occmz8LUz6BZruq8ZzXeuQ==
  hexapath-infra:zoneId:
    secure: AAABAOiD6WqReKiIROZT4kTlNiIV57slXYEHwd71SCxXx2IArVf61ZzXOKe8zyN6+hp2blA5sxhNou5DyRfxdw==
  cloudflare:apiToken:
    secure: AAABAIx/kUYGvM6RYX83n41rkh8OlpjlKyX5f+mlv1dxadBC9bHuFV62a1rVsKQk16X1F7zlZkUB5UBgx9di6hLcyp4ku5rhoQxY8jrrXujlG05fCg==
