config:
  hexapath-infra:projectName: hexapath-dev
  hexapath-infra:enableZeroTrust: "true"
  hexapath-infra:customDomain:
    secure: AAABAGv70Sjf4cKZIwsTER0Z4UcFBngmvhqLmIctxTfsJE5jlb7DybKPZ+28XkDkSQmPeNrTBYc=
  hexapath-infra:accountId:
    secure: AAABAH6vRLrMnhri5vP36JG4jRdEZTbbu6XP1BD7mdQfNkN0U2lxCUMHFW1Em5Y+5GlUBABiQN/oUeyX+Fd3yQ==
  hexapath-infra:zoneId:
    secure: AAABABILZWWUQWUKukkXR01tZCi2ngPe/Ms3Qknapedh4azReC68OdccxUxPqAibyTDiGISPoWKfUUmQbP7dwA==
  cloudflare:apiToken:
    secure: AAABANi0aY5xY0To7KS54/68rYixXdyzs5KoUR04Ht4ZhOUq+YRlBTkPYScL9TBnVELR4YzNigFnEhaJuZGgbtp9Bb3n2jQnX+I3MWm+KCllkd7kQg==
  hexapath-infra:accessEmails:
    secure: AAABAHVFO/hHpWX3mAAwPtuE38AOxo2g9OiY7iSe78z86wBuFbIr8CGfTyc/7jI5QwY2M8/qGrWB
